spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://dlutlgy.top/
          predicates:
            - Query=url,lgy
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product-route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            ##- RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}


##前端項目，/api