spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://dlutlgy.top/
          predicates:
            - Query=url,lgy
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq