spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      alicloud:
        access-key: LTAI5tJyJsmpWJFd6CTUh48V
        secret-key: AqN65J0Xa3NujWLsNgwwpfxuT4r8h5
        oss:
          endpoint: https://oss-cn-beijing.aliyuncs.com
          bucket: gulimall-lgy

  application:
    name: gulimall-third-party
server:
  port: 30000